name: spooky
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

# flutter pub upgrade --major-versions 
dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2

  # mvvm
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  responsive_builder: ^0.4.1
  logger: ^1.1.0
  get_it: ^7.2.0
  auto_route: ^3.2.1
  injectable: ^1.5.0
  intl: ^0.17.0
  easy_localization: ^3.0.0
  flutter_quill: ^3.0.4
  swipeable_page_route: ^0.2.4
  flutter_secure_storage: ^5.0.2
  adaptive_dialog: ^1.2.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  
  # mvvm
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/fonts/Quicksand/OFL.txt

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-SemiBold.ttf
