name: spooky
description: Minimalist application to write stories, notes, diary!
publish_to: none
version: 1.2.0+46
environment:
  sdk: ">=2.12.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.6.3
  animated_clipper: ^0.2.0+2
  animations: ^2.0.3
  audioplayers: ^0.20.1
  auto_route: ^4.0.1
  awesome_notifications: ^0.7.0-beta.4
  azlistview: ^2.0.0
  bubble_lens:
    git:
      url: git@github.com:juniorise/bubble_lens.git
      ref: main
  cached_network_image: ^3.2.1
  community_material_icon: ^5.9.55
  copy_with_extension: ^4.0.2
  cupertino_icons: ^1.0.4
  desktop_window: ^0.4.0
  dynamic_color: ^1.3.0
  easy_localization: ^3.0.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_cupertino_datetime_picker:
    git:
      url: git@github.com:juniorise/flutter_cupertino_datetime_picker.git
      ref: 3.0.1
  flutter_facebook_auth: ^4.3.4
  flutter_markdown: ^0.6.10+1
  flutter_phoenix: ^1.0.0
  flutter_quill: ^5.0.3
  flutter_screen_lock: ^5.0.12
  flutter_secure_storage: ^5.0.2
  flutter_sticky_header: ^0.6.3
  flutter_weather_bg_null_safety:
    git:
      url: git@github.com:juniorise/flutter_weather_bg_null_safety.git
      ref: 1.0.0
  fluttertoast: ^8.0.9
  fuzzy: ^0.4.0-nullsafety.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  googleapis: ^8.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  in_app_purchase: ^3.0.4
  in_app_purchase_android: ^0.2.2+6
  json_annotation: ^4.5.0
  just_audio: ^0.9.24
  local_auth: ^2.1.0
  logger: ^1.1.0
  material_color_utilities: ^0.1.4
  miniplayer: ^1.0.1
  package_info_plus: ^1.3.0
  path: ^1.8.1
  path_provider: ^2.0.10
  provider: ^6.0.3
  quick_actions: ^0.6.0+11
  rect_getter: ^1.1.0
  responsive_builder: ^0.4.2
  restart_app: ^1.1.0+1
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  swipeable_page_route: ^0.2.6
  timezone: ^0.8.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  wave: ^0.2.0
  cloud_firestore: ^3.1.17
  encrypt: ^5.0.1
  html_character_entities: ^1.0.0+1
  simple_animations: ^4.0.2
  launch_review: ^3.0.1
  in_app_update: ^3.0.0
  flutter_custom_tabs: ^1.0.4
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.14.0
  overscroll_pop: ^0.0.9
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  flat_buffers: ^2.0.5
  device_info_plus: ^3.2.4
  app_settings: ^4.1.6
  flutter_signin_button: ^2.0.0
  visibility_detector: ^0.3.3
  flutter_countdown_timer: ^4.1.0
  day_night_time_picker: ^1.1.2
  # for ObjectBox Sync
  # objectbox_sync_flutter_libs

  # unused:
  # injectable: ^1.5.3
  # open_file: ^3.2.1
  # scroll_to_index: ^3.0.1
  # stacked_services: ^0.8.25
  # visibility_detector: ^0.3.3
  # intl: ^0.17.0
  # flutter_keyboard_visibility: ^5.2.0
  # open_settings: ^2.0.2
  # googleapis_auth: ^1.3.1
  # simple_animations: ^4.0.2
  # expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  copy_with_extension_gen: ^4.0.2
  dependency_validator: ^3.2.0 # pub run dependency_validator
  flutter_app_name: ^0.1.1
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  objectbox_generator: any
  flutter_native_splash: ^2.2.0+1

flutter_app_name:
  name: "Spooky"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/
    - assets/translations/
    - assets/sounds/sounds.json
