name: spooky
description: Minimalist application to write stories, notes, diary!
publish_to: none
version: 1.0.0+11
environment:
  sdk: ">=2.12.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  responsive_builder: ^0.4.1
  swipeable_page_route: ^0.2.6
  adaptive_dialog: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  flutter_quill: # ^4.1.9
    git:
      url: https://github.com/myfknoll/flutter-quill.git
  flutter_cupertino_datetime_picker:
    git:
      url: git@github.com:juniorise/flutter_cupertino_datetime_picker.git
      ref: 3.0.1
  stacked_services: ^0.8.16
  logger: ^1.1.0
  auto_route: ^4.0.1
  path_provider: ^2.0.8
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  easy_localization: ^3.0.0
  timezone: ^0.8.0
  scroll_to_index: ^2.1.1
  audioplayers: ^0.20.1
  rect_getter: ^1.1.0
  flutter_keyboard_visibility: ^5.1.1
  visibility_detector: ^0.3.0
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0
  package_info_plus: ^1.3.0
  fluttertoast: ^8.0.8
  bubble_lens:
    git:
      url: git@github.com:juniorise/bubble_lens.git
      ref: main
  desktop_window: ^0.4.0
  local_auth: ^2.0.0
  flutter_screen_lock: ^5.0.6
  open_settings: ^2.0.2
  open_file: ^3.2.1
  quick_actions: ^0.6.0+9
  expandable_text: ^2.2.0
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  firebase_core: ^1.13.1
  awesome_notifications: ^0.7.0-beta.3
  provider: ^6.0.2
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  community_material_icon: ^5.9.55
  animated_clipper: ^0.2.0+2
  cached_network_image: ^3.2.0
  fuzzy: 0.4.0-nullsafety.0
  flutter_sticky_header: ^0.6.1
  azlistview: ^2.0.0
  in_app_purchase: ^3.0.2
  simple_animations: ^4.0.1
  wave: ^0.2.0
  miniplayer: ^1.0.1
  firebase_storage: ^10.2.9
  flutter_weather_bg_null_safety:
    git:
      url: git@github.com:juniorise/flutter_weather_bg_null_safety.git
      ref: 1.0.0
  just_audio: ^0.9.21
  sign_in_with_apple: ^3.3.0
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.3.1
  firebase_auth: ^3.3.11
  copy_with_extension_gen: ^4.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  tuple: ^2.0.0
  shared_preferences: ^2.0.15
  copy_with_extension: ^4.0.0
  animations: ^2.0.2
  path: ^1.8.1
  in_app_purchase_android: ^0.2.2+5
  dynamic_color: ^1.2.2
  material_color_utilities: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  # injectable_generator: ^1.5.3

flutter_app_name:
  name: "Spooky"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/
    - assets/translations/
    - backups/sounds.json
