name: spooky
description: Minimalist application to write stories, notes, diary!
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  responsive_builder: ^0.4.1
  swipeable_page_route: ^0.2.6
  adaptive_dialog: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  stacked: ^2.2.8
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  flutter_quill: ^4.0.1
  flutter_cupertino_datetime_picker:
    git:
      url: git@github.com:juniorise/flutter_cupertino_datetime_picker.git
      ref: 3.0.1
  stacked_services: ^0.8.16
  logger: ^1.1.0
  auto_route: ^3.2.2
  path_provider: ^2.0.8
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  easy_localization: ^3.0.0
  timezone: ^0.8.0
  scroll_to_index: ^2.1.1
  flutter_local_notifications: ^9.2.0
  audioplayers: ^0.20.1
  rect_getter: ^1.1.0
  flutter_keyboard_visibility: ^5.1.1
  visibility_detector: ^0.2.2
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0
  package_info_plus: ^1.3.0
  fluttertoast: ^8.0.8
  bubble_lens: ^2.0.0
  desktop_window: ^0.4.0
  local_auth: ^1.1.11
  flutter_screen_lock: ^5.0.6
  open_settings: ^2.0.2
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.1
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  # injectable_generator: ^1.5.3

flutter_app_name:
  name: "Spooky"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/fonts/Quicksand/OFL.txt

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-SemiBold.ttf
